name: Release Candidate
on:
  pull_request:
    types: [closed]
    branches: [develop]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install npm dependencies
        run: npm ci

      - name: Set user
        run: git config user.name Amira-Mohiey && git config user.email amiramohiey92@gmail.com

      - name: Build
        run: npm run build

      - name: Default Release
        id: defaultReleaseStep
        run: echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
       
      - name: Release Type
        id: releaseTypeStep
        run: |
          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'patch') }} = "true" ]]; then
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          fi

          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'minor') }} = "true" ]]; then
            echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          fi

          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'major') }} = "true" ]]; then
            echo "RELEASE_TYPE=major" >> $GITHUB_ENV
          fi
            
      - name: Release
        run: npm run release:rc $RELEASE_TYPE 
        id: releaseStep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}